import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

const textureDir = join(process.cwd(), 'public/textures');
const outputPath = join(process.cwd(), 'lib/texture-revisions.ts');

async function imageFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) return imageFiles(path);
      return /\.(jpe?g|png|webp)$/i.test(entry.name) ? [path] : [];
    }),
  );
  return nested.flat();
}

const revisions: Record<string, string> = {};
for (const path of (await imageFiles(textureDir)).sort()) {
  const name = relative(textureDir, path).split(sep).join('/');
  revisions[name] = createHash('sha256')
    .update(await readFile(path))
    .digest('hex')
    .slice(0, 16);
}

const source = `// Generated by scripts/generate-texture-revisions.ts.\nexport const textureFileRevisions: Record<string, string> = ${JSON.stringify(revisions, null, 2)};\n`;
let previous = '';
try {
  previous = await readFile(outputPath, 'utf8');
} catch {
  // The first generation creates the module imported by texture-quality.ts.
}
if (previous !== source) await writeFile(outputPath, source);
